2024-05-17 20:43:18,604 - aiogram.dispatcher - INFO - Start polling
2024-05-17 20:43:18,644 - aiogram.dispatcher - INFO - Run polling for bot @Events_Isoteric_bot id=7050859913 - 'EventsIsoteric'
2024-05-17 20:43:18,981 - aiogram.event - INFO - Update id=442792186 is handled. Duration 172 ms by bot id=7050859913
2024-05-17 20:43:18,987 - aiogram.event - INFO - Update id=442792184 is handled. Duration 178 ms by bot id=7050859913
2024-05-17 20:43:19,015 - aiogram.event - INFO - Update id=442792185 is handled. Duration 206 ms by bot id=7050859913
2024-05-17 20:43:19,032 - aiogram.event - INFO - Update id=442792183 is handled. Duration 224 ms by bot id=7050859913
2024-05-17 20:44:14,468 - aiogram.event - INFO - Update id=442792187 is handled. Duration 313 ms by bot id=7050859913
2024-05-17 20:54:51,923 - aiogram.dispatcher - INFO - Start polling
2024-05-17 20:54:51,965 - aiogram.dispatcher - INFO - Run polling for bot @Events_Isoteric_bot id=7050859913 - 'EventsIsoteric'
2024-05-17 20:54:52,314 - aiogram.event - INFO - Update id=442792192 is handled. Duration 176 ms by bot id=7050859913
2024-05-17 20:54:52,333 - aiogram.event - INFO - Update id=442792190 is handled. Duration 197 ms by bot id=7050859913
2024-05-17 21:00:06,877 - aiogram.dispatcher - INFO - Start polling
2024-05-17 21:00:06,926 - aiogram.dispatcher - INFO - Run polling for bot @Events_Isoteric_bot id=7050859913 - 'EventsIsoteric'
2024-05-17 21:00:14,125 - aiogram.event - INFO - Update id=442792193 is handled. Duration 516 ms by bot id=7050859913
2024-05-17 21:00:15,989 - aiogram.event - INFO - Update id=442792194 is handled. Duration 126 ms by bot id=7050859913
2024-05-17 21:00:40,530 - aiogram.event - INFO - Update id=442792195 is handled. Duration 211 ms by bot id=7050859913
2024-05-17 21:01:21,854 - aiogram.event - INFO - Update id=442792196 is handled. Duration 172 ms by bot id=7050859913
2024-05-17 21:01:33,922 - aiogram.event - INFO - Update id=442792197 is handled. Duration 91 ms by bot id=7050859913
2024-05-17 21:01:36,054 - aiogram.event - INFO - Update id=442792198 is handled. Duration 131 ms by bot id=7050859913
2024-05-17 21:01:38,302 - aiogram.event - INFO - Update id=442792199 is handled. Duration 73 ms by bot id=7050859913
2024-05-17 21:01:53,598 - aiogram.event - INFO - Update id=442792200 is handled. Duration 196 ms by bot id=7050859913
2024-05-17 21:01:56,276 - aiogram.event - INFO - Update id=442792201 is handled. Duration 65 ms by bot id=7050859913
2024-05-17 21:02:08,750 - aiogram.event - INFO - Update id=442792202 is handled. Duration 80 ms by bot id=7050859913
2024-05-17 21:02:11,598 - aiogram.event - INFO - Update id=442792203 is handled. Duration 59 ms by bot id=7050859913
2024-05-17 21:02:26,808 - aiogram.event - INFO - Update id=442792204 is handled. Duration 161 ms by bot id=7050859913
2024-05-17 21:02:30,074 - aiogram.event - INFO - Update id=442792205 is handled. Duration 98 ms by bot id=7050859913
2024-05-17 21:02:41,416 - aiogram.event - INFO - Update id=442792206 is handled. Duration 199 ms by bot id=7050859913
2024-05-17 21:02:44,503 - aiogram.event - INFO - Update id=442792207 is handled. Duration 78 ms by bot id=7050859913
2024-05-17 21:02:49,501 - aiogram.event - INFO - Update id=442792208 is handled. Duration 80 ms by bot id=7050859913
2024-05-17 21:02:51,157 - aiogram.event - INFO - Update id=442792209 is not handled. Duration 219 ms by bot id=7050859913
2024-05-17 21:02:51,161 - aiogram.event - ERROR - Cause exception while process update id=442792209 by bot id=7050859913
TelegramBadRequest: Telegram server says - Bad Request: chat not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/middlewares/user_context.py", line 49, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/router.py", line 137, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/root/mp/handlers/other.py", line 492, in send
    msg = await bot.send_message(-1002001083190, mess, parse_mode='HTML')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/client/bot.py", line 2873, in send_message
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/client/bot.py", line 509, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/client/session/aiohttp.py", line 178, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: chat not found
